apiVersion: v2
name: mlflow
description: A Helm chart for MLflow (https://mlflow.org/)
home: https://github.com/dingobar/charts
sources:
  - https://github.com/dingobar/charts
  - https://github.com/dingobar/images
maintainers:
  - name: Martin Morset
    url: https://github.com/dingobar
icon: https://mlflow.org/docs/latest/_static/MLflow-logo-final-black.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.8.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.29.0"

# Chart dependencies MinIO and postgresql
# Depending on your Kubernetes configuration, you probably don't want to enable these in production
# I recommend you offload all state to hosted services like AWS S3 and AWS RDS for PostgreSQL.
dependencies:
  - name: minio
    repository: https://charts.bitnami.com/bitnami
    version: 11.5.1
    condition: minio.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.2.4
    condition: postgresql.enabled
